name: Backlog Issue
description: ざっくり洗い出した段階の Issue を作成
title: "[Backlog] "
labels: ["status/backlog", "type/feature"]
body:
  - type: markdown
    attributes:
      value: |
        ## Backlog Issue テンプレート
        詳細設計が完了したら `status/ready` ラベルに変更し、テンプレートを更新してください。

  - type: textarea
    id: dependencies
    attributes:
      label: 依存関係
      description: 依存する Issue があれば記載（例: Blocked by #1, #2）
      placeholder: |
        Blocked by #N, #M
    validations:
      required: false

  - type: textarea
    id: overview
    attributes:
      label: 概要
      description: 何を実現したいか
      placeholder: |
        チームエンティティを実装し、参加者がチームに所属できるようにする
    validations:
      required: true

  - type: textarea
    id: background
    attributes:
      label: 背景・動機
      description: なぜ必要か
      placeholder: |
        仕様書のチーム管理機能を実現するため
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: 受け入れ条件（ざっくり）
      description: 完了とみなす条件
      placeholder: |
        - [ ] チームエンティティが作成できる
        - [ ] チーム名のバリデーションが機能する
        - [ ] テストが通る
    validations:
      required: true

  - type: textarea
    id: spec
    attributes:
      label: 関連仕様
      description: 仕様書の該当セクションへのリンク
      placeholder: |
        - [仕様書 - チーム管理](docs/仕様書.md#チーム管理)
    validations:
      required: false

  - type: dropdown
    id: domain
    attributes:
      label: ドメイン
      options:
        - participant
        - team
        - task
        - web
    validations:
      required: true

  - type: dropdown
    id: size
    attributes:
      label: サイズ
      options:
        - S (1-2h)
        - M (半日)
        - L (1日以上)
    validations:
      required: true

  - type: dropdown
    id: stream
    attributes:
      label: ストリーム
      options:
        - team-domain
        - task-domain
        - notification
        - integration
        - frontend
    validations:
      required: true
